#!/bin/bash
### BEGIN INIT INFO
# Provides:          europeana-publisher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the daemon service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

[ -R /etc/default/europeana-publisher ] && . /etc/default/europeana-publisher

JAVA_HOME=${JAVA_HOME:=/usr/lib/jvm/java-7-oracle}
EUROPEANA_PUBLISHER=${EUROPEANA_PUBLISHER:=/opt/publisher}
LIB_DAEMON=${LIB_DAEMON:=$EUROPEANA_PUBLISHER/lib/commons-daemon.jar}
ERR_FILE=${ERR_FILE:=$EUROPEANA_PUBLISHER/err}
RUNAS=root

PIDFILE=/var/run/publisher.pid


start() {
  if [ -f '$PIDFILE' ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting publisher...' >&2
  DATE=`echo $(date +%D) | sed -e "s/\//-/g"`
  LOGFILE="/var/log/publisher_$DATE.log"
  echo 'logfile created: '  $LOGFILE
  if [ -f "$LOGFILE" ]; then
     su -c "rm -f $LOGFILE"
  fi
  SCRIPT="/usr/bin/jsvc -home $JAVA_HOME -outfile $LOGFILE -errfile $ERR_FILE -server -XX:+UseNUMA -XX:+UseCondCardMark -XX:-UseBiasedLocking -XX:+UseParallelGC -Xms1g -Xmx4g -Xss1M -Dlog4j.configurationFile=$EUROPEANA_PUBLISHER/extra-files/log4j2.xml -cp $LIB_DAEMON:$EUROPEANA_PUBLISHER/publisher.jar eu.europeana.publisher.PublisherDaemon $EUROPEANA_PUBLISHER/extra-files/publishing.conf"

  cd $EUROPEANA_PUBLISHER
  local CMD="$SCRIPT > \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
   echo "killing every europeana publisher started"
   su -c "ps -ef | grep '-errfile $ERR_FILE -server -XX:+UseNUMA -XX:+UseCondCardMark -XX:-UseBiasedLocking -XX:+UseParallelGC -Xms1g -Xmx4g -Xss1M -Dlog4j.configurationFile=$EUROPEANA_PUBLISHER/extra-files/log4j2.xml -cp $LIB_DAEMON:$EUROPEANA_PUBLISHER/publisher.jar eu.europeana.publisher.PublisherDaemon $EUROPEANA_PUBLISHER/extra-files/publishing.conf$' | awk '{print \$2}' | xargs kill -15"
}

uninstall() {
  echo -n "Are you really sure you want to uninstall europeana publisher ? This cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    rm -rfv "$EUROPEANA_PUBLISHER"
    echo "Notice: log file(s) will not be removed: /var/log/publisher*.log" >&2
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac