#!/bin/bash
### BEGIN INIT INFO
# Provides:          europeana-publisher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the daemon service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO
EUROPEANA_PUBLISHER=${EUROPEANA_PUBLISHER:=/opt/publisher}
SCRIPT="java -server -XX:+UseNUMA -XX:+UseCondCardMark -XX:-UseBiasedLocking -XX:+UseParallelGC -Xms1g -Xmx4g -Xss1M -Dlog4j.configurationFile=$EUROPEANA_PUBLISHER/extra-files/log4j2.xml -cp $EUROPEANA_PUBLISHER/publisher.jar eu.europeana.publisher.PublisherMain $EUROPEANA_PUBLISHER/extra-files/publishing.conf"
RUNAS=root

PIDFILE=/var/run/publisher.pid


start() {
  if [ -f '$PIDFILE' ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  
  echo 'Starting publisher...' >&2
  LOGFILE=/var/log/publisher_$(date +%u).log
  echo 'logfile created: '  $LOGFILE
  if [ -f "$LOGFILE" ]; then
     su -c "rm -f $LOGFILE"
  fi
  echo $SCRIPT

  cd $EUROPEANA_PUBLISHER
  local CMD="$SCRIPT > \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if  !kill -0 $(cat "$PIDFILE"); then
    echo 'publisher not running' >&2
    return 1
  fi
  echo 'Stopping publisher...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall harvester slave? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file will not be removed: /var/log/publisher*.log" >&2
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
